name: smoke

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test] ruff

      - name: Format check (ruff)
        run: ruff format --check .

      - name: Lint (ruff)
        run: ruff check .

      - name: Tests (pytest -q)
        run: pytest -q

